name: Build and Deploy EmployeeApp

on:
  push:
    branches:
      - main  # This means the pipeline will run every time code is pushed to the main branch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # Make sure this matches the version you used to build the app locally

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EmployeeApp'  # Make sure this matches **exactly** the name of your Azure Web App
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
